In [ ]:
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [ ]:
import torch.nn as nn

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [ ]:
inputs =  torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [ ]:
#define dataset
from torch.utils.data import TensorDataset, DataLoader
dataset = TensorDataset(inputs, targets)
dataset[0:4]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.]]))

In [ ]:
# Define data loader
batch_size = 6
dl = DataLoader(dataset, batch_size, shuffle=True)
next(iter(dl))

[tensor([[102.,  43.,  37.],
         [ 91.,  88.,  64.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [102.,  43.,  37.],
         [ 73.,  67.,  43.]]), tensor([[ 22.,  37.],
         [ 81., 101.],
         [ 22.,  37.],
         [103., 119.],
         [ 22.,  37.],
         [ 56.,  70.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [ ]:
# Define model
model = nn.Linear(3, 2)
print(model.weight, end="\n---------\n")
print(model.bias)

Parameter containing:
tensor([[-0.2071, -0.3320, -0.0652],
        [-0.1110,  0.2560,  0.2746]], requires_grad=True)
---------
Parameter containing:
tensor([0.0921, 0.3070], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [ ]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [ ]:
# Import nn.functional
import torch.nn.functional as F

# Define loss function
loss_fn = F.mse_loss

loss = loss_fn(model(inputs) , targets)
print(loss)

tensor(11183.3008, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [ ]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))

In [ ]:
# Train the model for 100 epochs
fit(100 , model , loss_fn, opt)

# Generate predictions
preds = model(inputs)
print('\n', preds)

Training loss:  tensor(4.7941, grad_fn=<MseLossBackward>)

 tensor([[ 57.4645,  70.6447],
        [ 81.1244,  99.0590],
        [120.5678, 136.0859],
        [ 22.6848,  38.4798],
        [ 99.1279, 115.5410],
        [ 57.4645,  70.6447],
        [ 81.1244,  99.0590],
        [120.5678, 136.0859],
        [ 22.6848,  38.4798],
        [ 99.1279, 115.5410],
        [ 57.4645,  70.6447],
        [ 81.1244,  99.0590],
        [120.5678, 136.0859],
        [ 22.6848,  38.4798],
        [ 99.1279, 115.5410]], grad_fn=<AddmmBackward>)


In [ ]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Now we can define the model, optimizer and loss function exactly as before.

In [ ]:
fit(100 , model , loss_fn, opt)

Training loss:  tensor(2.8572, grad_fn=<MseLossBackward>)




---



In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [ ]:
# weights and biases
weights = np.random.rand(2, 3)
biases = np.random.rand(15, 2)
print("Weights  :  ", weights, sep='\n')
print("Biases  :  ", biases, sep="\n")

Weights  :  
[[0.15889786 0.30809507 0.97723848]
 [0.99365289 0.32188508 0.62443962]]
Biases  :  
[[9.25900434e-01 5.72090334e-01]
 [4.94034656e-02 4.64799266e-01]
 [7.75309160e-02 3.74175258e-01]
 [9.11091145e-01 9.28912241e-01]
 [1.90770108e-01 1.01280005e-01]
 [3.65506576e-01 6.56335188e-01]
 [3.76629570e-01 7.75377862e-01]
 [7.69541757e-02 8.65769650e-01]
 [3.23984404e-01 1.68770441e-01]
 [5.95965606e-01 4.28800490e-01]
 [3.63246597e-01 9.11912280e-01]
 [7.86858836e-01 3.65211112e-03]
 [1.81152514e-01 6.68850059e-01]
 [8.39856794e-01 4.27367094e-04]
 [7.47349697e-01 3.78112774e-01]]


In [ ]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [ ]:
# Generate predictions
pred = model(inputs)

# Compare with targets
print("Predictions : ", pred, sep="\n")
print("\nTargets : ", targets, sep="\n")

Predictions : 
[[ 75.18906814 121.52595554]
 [104.16473707 159.17723526]
 [111.86621548 166.1720758 ]
 [ 66.5245841  139.22683154]
 [109.13854232 143.27507081]
 [ 74.62867428 121.61020039]
 [104.49196317 159.48781386]
 [111.86563874 166.66367019]
 [ 65.93747736 138.46668974]
 [109.54373782 143.60259129]
 [ 74.6264143  121.86577749]
 [104.90219244 158.71608811]
 [111.96983708 166.4667506 ]
 [ 66.45334975 138.29834666]
 [109.69512191 143.55190358]]

Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [ ]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [ ]:
# Compute loss
loss = mse(pred, targets)
print(loss)

4212.727087920074


In [ ]:
# compute gradients
biases_grad = (pred - targets) * 2/x_shape[0]
weights_grad = (np.matmul(np.transpose((pred - targets)), inputs)) * 2/x_shape[0]

print("Weights gradient  :  ",weights_grad, sep="\n")
print("\nBiases gradient  :  ",biases_grad, sep="\n")

Weights gradient  :  
[[3144.36566689 1961.67479587 1597.58057652]
 [9611.46031891 7911.3457045  5342.37192436]]

Biases gradient  :  
[[ 2.55854242  6.87012741]
 [ 3.08863161  7.7569647 ]
 [-0.95117127  4.42294344]
 [ 5.93661121 13.63024421]
 [ 0.81847231  3.23667611]
 [ 2.48382324  6.88136005]
 [ 3.13226176  7.79837518]
 [-0.95124817  4.48848936]
 [ 5.85833031 13.52889197]
 [ 0.87249838  3.28034551]
 [ 2.48352191  6.915437  ]
 [ 3.18695899  7.69547841]
 [-0.93735506  4.46223341]
 [ 5.9271133  13.50644622]
 [ 0.89268292  3.27358714]]


In [ ]:
# Adjust weights
weights -= weights_grad * 1e-4
biases -= biases_grad * 1e-4

In [ ]:
print("Weights  :  ", weights, sep='\n')
print("\nBiases  :  ", biases, sep="\n")

Weights  :  
[[-0.18698237  0.09231084  0.80150461]
 [-0.06360775 -0.54836294  0.03677871]]

Biases  :  
[[ 0.92561899  0.57133462]
 [ 0.04906372  0.463946  ]
 [ 0.07763554  0.37368873]
 [ 0.91043812  0.92741291]
 [ 0.19068008  0.10092397]
 [ 0.36523336  0.65557824]
 [ 0.37628502  0.77452004]
 [ 0.07705881  0.86527592]
 [ 0.32333999  0.16728226]
 [ 0.59586963  0.42843965]
 [ 0.36297341  0.91115158]
 [ 0.78650827  0.00280561]
 [ 0.18125562  0.66835921]
 [ 0.83920481 -0.00105834]
 [ 0.7472515   0.37775268]]


In [ ]:
# Calculate loss
pred = model(inputs)
loss = mse(pred, targets)
print(loss)

24760.57018066554


In [ ]:
# repeating same for 200 times
for i in range(200):
    pred = model(inputs)
    loss = mse(pred, targets)
    
    biases_grad = ((((inputs@np.transpose(weights)) + biases) - targets)) * 2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights)) + biases) - targets)), inputs)) * 2/x_shape[0]

    weights -= weights_grad * 1e-4
    biases -= biases_grad * 1e-4

In [ ]:
# Calculate loss
pred = model(inputs)
loss = mse(pred, targets)
print(loss)

1.3713379933587668e+169


In [ ]:
# Print predictions
print(pred)

[[-8.34132791e+83 -2.86184797e+84]
 [-1.09608887e+84 -3.76059992e+84]
 [-1.29532690e+84 -4.44417088e+84]
 [-8.30482218e+83 -2.84932313e+84]
 [-1.05075472e+84 -3.60506181e+84]
 [-8.34132791e+83 -2.86184797e+84]
 [-1.09608887e+84 -3.76059992e+84]
 [-1.29532690e+84 -4.44417088e+84]
 [-8.30482218e+83 -2.84932313e+84]
 [-1.05075472e+84 -3.60506181e+84]
 [-8.34132791e+83 -2.86184797e+84]
 [-1.09608887e+84 -3.76059992e+84]
 [-1.29532690e+84 -4.44417088e+84]
 [-8.30482218e+83 -2.84932313e+84]
 [-1.05075472e+84 -3.60506181e+84]]


In [ ]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
